In [1]:
import numpy as np

np_range = np.arange(0, 11)
print(np_range)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
np_ran = np.arange(0.5, 5.25, 0.25)
print(np_ran)

[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [19]:
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
zero_mul = np.zeros((4, 3))
print(zero_mul)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
lin_array = np.linspace(2, 12, 5, dtype=int)
print(lin_array)

[ 2  4  7  9 12]


In [25]:
lin_array = np.linspace(2, 12, 5)
print(lin_array)

[ 2.   4.5  7.   9.5 12. ]


In [23]:
lin_arr = np.linspace(3, 9, 4, dtype=int)
print(lin_arr)

[3 5 7 9]


In [27]:
lin_arr = np.linspace(3, 9, 4)
print(lin_arr)

[3. 5. 7. 9.]


In [29]:
random_array = np.random.rand(2, 4)  
print(random_array)

[[0.02092752 0.76790698 0.21124405 0.35927549]
 [0.14254552 0.55252044 0.2924782  0.86314032]]


In [31]:
random_arr = np.random.randint(10, 21, (3, 3))  
print(random_arr)

[[11 14 20]
 [19 12 11]
 [13 15 13]]


In [33]:
random_array = np.random.rand(2, 4)  
print(random_array)
reshaped_array = random_array.reshape(8, 1)
print(reshaped_array)

[[0.47828611 0.82446712 0.38484239 0.75985668]
 [0.63624613 0.96494257 0.06361578 0.21783468]]
[[0.47828611]
 [0.82446712]
 [0.38484239]
 [0.75985668]
 [0.63624613]
 [0.96494257]
 [0.06361578]
 [0.21783468]]


In [ ]:
You need to pay attention when using the reshape function - 
Matching number of elements, a copy is not always created, the Order of the shape and mismatched dimensions error.

In [ ]:
If we generate random numbers using a fixed seed, we will always get the same sequence of random numbers in every run of the program.
This causes every call to functions like np.random.rand() or np.random.randint() to generate the same results in every run of the code.

The main advantage of using a seed is reproducibility -
Reproducibility of results, collaboration with others, control of a random process and ability to analyze results.